services:

  localstack:
    container_name: localstack-todo
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      DYNAMODB_SHARE_DB: 1
    volumes:
      - ./localstack/:/etc/localstack/init/ready.d/
